<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/22 16:38:14
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
