<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/22 12:22:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'Savenkova29',
  'name' => 'doctrine',
)),);
